### ISSUE TITLE
NoClassDefFoundError: net/minecraft/class_437

### ISSUE THREAD

**Issue by EazyFTW** [Roundaround/mc-fabric-stackables#3]
I am getting this error when attempting to use with a server. (Because the server doesn't have the screen class as shown here: https://linkie.shedaniel.dev/mappings?namespace=yarn&version=1.20&search=class_437)

```[21:00:32] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'stackables'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at me.roundaround.stackables.roundalib.config.option.ConfigOption$ValueChangeListeners.invoke(ConfigOption.java:234) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.roundalib.config.option.ConfigOption.setValue(ConfigOption.java:87) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.roundalib.config.option.ConfigOption.deserialize(ConfigOption.java:120) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.roundalib.config.ModConfig.lambda$loadFromFile$0(ModConfig.java:81) ~[stackables-1.2.0+1.20.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.roundaround.stackables.roundalib.config.ModConfig.lambda$loadFromFile$1(ModConfig.java:77) ~[stackables-1.2.0+1.20.jar:?]
        at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:708) ~[?:?]
        at me.roundaround.stackables.roundalib.config.ModConfig.loadFromFile(ModConfig.java:76) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.roundalib.config.ModConfig.init(ModConfig.java:37) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.StackablesMod.onInitialize(StackablesMod.java:18) ~[stackables-1.2.0+1.20.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.roundaround.stackables.roundalib.config.option.ConfigOption$ValueChangeListeners.invoke(ConfigOption.java:234) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.roundalib.config.option.ConfigOption.setValue(ConfigOption.java:87) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.roundalib.config.option.ConfigOption.deserialize(ConfigOption.java:120) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.roundalib.config.ModConfig.lambda$loadFromFile$0(ModConfig.java:81) ~[stackables-1.2.0+1.20.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.roundaround.stackables.roundalib.config.ModConfig.lambda$loadFromFile$1(ModConfig.java:77) ~[stackables-1.2.0+1.20.jar:?]
        at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:708) ~[?:?]
        at me.roundaround.stackables.roundalib.config.ModConfig.loadFromFile(ModConfig.java:76) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.roundalib.config.ModConfig.init(ModConfig.java:37) ~[stackables-1.2.0+1.20.jar:?]
        at me.roundaround.stackables.StackablesMod.onInitialize(StackablesMod.java:18) ~[stackables-1.2.0+1.20.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 7 more```

**Comment by Roundaround** [comment]
Should be fixed in 1.2.1. Thanks for reporting and sorry for the trouble!
